### PR TITLE
Nested selectors handling

### PR DESCRIPTION
**Pull request by aczekajski**
This PR addresses https://github.com/Microsoft/typescript-styled-plugin/issues/26 by removing `_cssLanguageService` and using `_scssLanguageService` instead when invoking `doComplete` for code completion.

Since SCSS language provides some built-in function that are not supported by the styled-components, function `filterCompletionItems` is introduced. It allows several reasonable completion items kinds and a `CompletionItemKind.Function` which, for some reason, groups scss functions (like `darken`, not supported be styled components) with pseudo-classess and pseudo-elements (like `:hover` and `::after`, supported by styled-components). Thus, kind `Function` is allowed only when label begins with `:`.

### CODE REVIEW

**Comment by aczekajski** [comment]
Now several tests are failing because of strict checking of the number of completions in ``css`color:` ``. Version 0.3.1 returns 153 html colors and 4 prefixes `hsl`, `hsla`, `rgb`, `rgba`. My version doesn't return these four prefixes because SCSS provides them as functions and current filtering logic disallows them, hence failing the tests.

The questions is if we still want `hsl`, `hsla`, `rgb` and `rgba` returned in completions. I can add exceptions to these four and other CSS functions (see https://developer.mozilla.org/en-US/docs/tag/CSS%20Function for example) but also we can just change the `157` in test into `153`, leaving the CSS functions alone for the time being.

**Comment by mjbvz** [comment]
@aczekajski Thank you for looking into this!

Yes I think we still want `rgb`, `hsl`, etc. Adding exceptions for the common css functions should work. Please also add a simple test to make sure sass specific completions are being filtered out properly

**Comment by aczekajski** [comment]
I started investigating which functions we want to keep and which should be dropped and figured it's not as easy as it seems. Escpecially the details might be inaccurate. For example in CSS one can type `rgba(0, 0, 0, 0.3)` but in SCSS it is also possible to do something like `rgba(#000, 0.3)`. We don't want SCSS versions of functions descriptions to show.

So, instead I tried doing something that seems a bit untrustworthy but seems to work. I parsed the stylesheet with SCSS but invoked completion from CSS:
```ts
const stylesheet = this.scssLanguageService.parseStylesheet(doc);
const completions = this.cssLanguageService.doComplete(doc, this.toVirtualDocPosition(position), stylesheet);
```
without any completions filtering. This properly provides completions for CSS even in nested selectors. I'll do some more testing of possible scenarios.

**Comment by aczekajski** [comment]
@mjbvz I've added additional tests, to check if css functions are being returned while scss functions are not being returned, and to check if completions work for nested selector.

**Comment by mjbvz** [comment]
Thanks! Very cool.

Will publish an updated version with this fix shortly

**Comment by mjbvz** [comment]
Published with 0.4.0

**Comment by u3u** [comment]
Hello everyone, I updated the 0.4.0 version, but there is still a problem with the IntelliSense in the nested structure, look at the following GIF:

**Comment by u3u** [comment]
There is one more issue: 
it works when I use the hotkey to display the suggestion, but it does not work when I type directly.

**Comment by u3u** [comment]
In `injectGlobal` also does not work 😅

**Comment by mjbvz** [comment]
@u3u Please open new issues with code snippets for each problem

**Comment by aczekajski** [comment]
There's a chance that part of it is a problem with SCSS language service itself.

**Pull request merged**
