### PR TITLE
Add intellisense support for keyframes fixes #137

### LINKED ISSUE #136: Getting `} expectedts-styled-plugin(9999)` when using keyframes
I'm getting the following errors when using keyframes without interpolation:

- `} expectedts-styled-plugin(9999)`
- `at-rule or selector expectedts-styled-plugin(9999)`

```javascript
import styled, { css, keyframes } from 'styled-components';

const blink = keyframes`
  0% {
    opacity: 0;
  }

  100% {
    opacity: 1;
  }
`;

const blinkBox = styled.div`
  animation: ${css`
    ${blink} 700ms ease-out infinite alternate
  `};
`;
```

Screen Shot 2021-05-21 at 12 04 19

Screen Shot 2021-05-21 at 12 01 46

Screen Shot 2021-05-21 at 12 03 38

Each error appears twice. The errors disappear when I tweak it like this:

```javascript
const blink = keyframes`
  ${'0%'} {
    opacity: 0;
  }

  ${'100%'} {
    opacity: 1;
  }
`;
```
Which is ugly and shouldn't be necessary.

### LINKED ISSUE #137: Dynamically change wrapper based on tag used
Raised from https://github.com/styled-components/vscode-styled-components/issues/293
Feature in Styled Components: https://styled-components.com/docs/basics#animations

Hey @mjbvz do you know if its possible to dynamically change the [root](https://github.com/microsoft/typescript-styled-plugin/blob/main/src/_virtual-document-provider.ts#L24) based on the tag used?

In this case we want the keyframes`` tag to use a `@keyframes {` root instead of the traditional `:root {` version.
Seeing as there's no way of knowing which tag was used to trigger intellisense the only other option is to heuristically check the contents to know what wrapper to use. If there's percentage as the first token or from/to switch to `@keyframes {` wrapper

### PR DESCRIPTION
**Pull request by jasonwilliams**
- Dynamically set the wrapper to be `@keyframes {}` when the keyframes tag is used
- Pass context to offset functions so  they can calculate the correct wrapper length
- This uses a new utility function which will return the correct wrapper based on the context used.
- Update target output for TS
 - Add keyframes test for completions
 - Prettier

Fixes https://github.com/microsoft/typescript-styled-plugin/issues/137
Fixes #136
@mjbvz 

keyframes

### CODE REVIEW

**Review by mjbvz — CHANGES_REQUESTED** [review]
Thanks for looking into this!

The code changes look good. Could you please add a simple test for this feature so we don't accidentally break it in the future

**Comment by jasonwilliams** [comment]
@mjbvz here's some changes I made let me know if its enough.

 - Update tsconfig target output for TS (2019)
 - Add keyframes test for completions
 - Prettier has update the formatting of the test file

**Comment by jasonwilliams** [comment]
Ping @mjbvz

**Comment by mjbvz** [comment]
Thanks! Will push update shortly

**Pull request merged**
