### PR TITLE
build: update vscode-css-languageservice

### LINKED ISSUE #119: Update vscode-css-language service to 4.3.0
Update VSCode-css-language service to 4.3.0 

https://github.com/microsoft/vscode-css-languageservice/blob/master/CHANGELOG.md#430---2020-06-26

@mjbvz do you still maintain this repo?

### PR DESCRIPTION
**Pull request by hantatsang**
Close #119 

## Implementation

- Update `vscode-css-languageservice` to v5.1.0. 
- Also update `vscode-languageserver-types` to v3.16.0 due to compatibility with `vscode-css-languageservice`

### CODE REVIEW

**Comment by hantatsang** [comment]
Both before and after updating packages, running e2e tests fail for me:

```
  63 passing (2m)
  1 failing

  1) OutliningSpans
       should return basic css outlining spans:

      AssertionError: expected 3 to equal 2
      + expected - actual

      -3
      +2

      at Context.<anonymous> (e2e\tests\outliningSpans.js:22:16)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Is this expected on `main` branch?

**Comment by jasonwilliams** [comment]
> Both before and after updating packages, running e2e tests fail for me:

@hantatsang i had the same issue which is a shame, are you able to update the dependencies again and I can take a look

**Comment by hantatsang** [comment]
@jasonwilliams I just to upgraded to `vscode-css-languageservice@5.1.1` (latest). Still, the same test fails 🤔

**Comment by jasonwilliams** [comment]
Every e2e test fails for me I don't know if they're even working properly anymore. @mjbvz do you know?

**Comment by hantatsang** [comment]
All my tests also failed at first after this upgrade. But then I `cd e2e && npm i`, run test again and only the 1 test above failed

**Comment by jasonwilliams** [comment]
> All my tests also failed at first after this upgrade. But then I `cd e2e && npm i`, run test again and only the 1 test above failed

Yep i just noticed that too. I have the same single test failing now, thanks.

**Comment by jasonwilliams** [comment]
Looks like it used to return 2 spans at one point, now it returns 3. Here's what spans looks like:
```
[
  {
    textSpan: {
      start: {
        line: 1,
        offset: 14,
      },
      end: {
        line: 8,
        offset: 2,
      },
    },
    hintSpan: {
      start: {
        line: 1,
        offset: 14,
      },
      end: {
        line: 8,
        offset: 2,
      },
    },
    bannerText: "...",
    autoCollapse: false,
    kind: "code",
  },
  {
    textSpan: {
      start: {
        line: 2,
        offset: 1,
      },
      end: {
        line: 3,
        offset: 1,
      },
    },
    hintSpan: {
      start: {
        line: 2,
        offset: 1,
      },
      end: {
        line: 3,
        offset: 1,
      },
    },
    bannerText: "",
    autoCollapse: false,
    kind: "code",
  },
  {
    textSpan: {
      start: {
        line: 5,
        offset: 1,
      },
      end: {
        line: 6,
        offset: 1,
      },
    },
    hintSpan: {
      start: {
        line: 5,
        offset: 1,
      },
      end: {
        line: 6,
        offset: 1,
      },
    },
    bannerText: "",
    autoCollapse: false,
    kind: "code",
  },
]
```

**Comment by jasonwilliams** [comment]
@hantatsang i think the new output (above) is correct. It seems like it creates an extra span for the whole thing. So the test can be updated to accept that. Im guessing when this was originally written only the 2 inner blocks generated spans, but now it generates a span for the `const q` definition

**Comment by jasonwilliams** [comment]
Also @hantatsang does `npm run compile` work for you? I don't have your change checked out but i remember i was having issues before with that. Hopefully the types are now updated in tandem with css-language service

**Comment by jasonwilliams** [comment]
Changing to https://github.com/microsoft/typescript-styled-plugin/blob/main/e2e/tests/outliningSpans.js

```
        assert.strictEqual(spans.length, 3);

        const [span1, span2, span3] = spans;
        assertPosition(span2.textSpan.start, 2, 1);
        assertPosition(span2.textSpan.end, 3, 1);

        assertPosition(span3.textSpan.start, 5, 1);
        assertPosition(span3.textSpan.end, 6, 1);
```

works

**Comment by jasonwilliams** [comment]
@hantatsang could you change that file to this
```js
        assert.strictEqual(spans.length, 3);
        // The first span represents the root
        const [_, span2, span3] = spans;
        assertPosition(span2.textSpan.start, 2, 1);
        assertPosition(span2.textSpan.end, 3, 1);

        assertPosition(span3.textSpan.start, 5, 1);
        assertPosition(span3.textSpan.end, 6, 1);
        ```

**Comment by hantatsang** [comment]
Thanks, @jasonwilliams . Updated. Hope this will get reviewed & merged.

**Comment by jasonwilliams** [comment]
@mjbvz are you able to look at this also?

**Comment by mjbvz** [comment]
Thanks!

**Pull request merged**
